spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root 
    password: 
    driverClassName: com.mysql.jdbc.Driver 
  jackson: 
    serialization:
      FAIL_ON_EMPTY_BEANS: false 
  h2: 
    console: 
      settings:
        web-allow-others : true 
    enabled: true 
    path: /db 
  jpa: 
    hibernate: 
      ddl-auto: update
